### ISSUE TITLE
Add .gitignore

### ISSUE THREAD

**Issue by hugofqueiros** [gigigo-html5/gigigo-react-webpack#1]
Add .gitignore and delete DS_STORE file and dist folder (it shouldn't be in the repo) add the folder to the following gitignore file example

# Logs
logs
*.log
npm-debug.log*

# Runtime data
pids
*.pid
*.seed

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage

# nyc test coverage
.nyc_output

# Grunt intermediate storage (http://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# node-waf configuration
.lock-wscript

# Compiled binary addons (http://nodejs.org/api/addons.html)
build/Release

# Dependency directories
node_modules
jspm_packages

# Optional npm cache directory
.npm

# Optional REPL history
.node_repl_history

# IDE
.idea
.DS_Store

**Comment by marisaoliva** [comment]
All right , I forgot , thank you very much!!!
