### ISSUE TITLE
add .editorconfig file

### ISSUE THREAD

**Issue by hugofqueiros** [gigigo-html5/gigigo-react-webpack#2]
[*]
indent_style = space
end_of_line = lf
indent_size = 2
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[*.md]
max_line_length = 0
trim_trailing_whitespace = false

**Comment by marisaoliva** [comment]
thanks you. I forgot!!. Perhaps we should create a standard file for department and use the same file for all project.  

Meanwhile use this
